// Historia de ejemplo (ficticia) con la redacción esperada. La usan las pruebas y el Word de muestra.

export const DNI_EJEMPLO = '40123456';

export const VALORES_EJEMPLO: Record<string, string> = {
  'ect.ectoscopia':
    'Paciente en aparente regular estado general, buen estado nutricional y buen estado de hidratación, que aparenta la edad que refiere. Despierto, lúcido, orientado en tiempo, espacio y persona, colaborador al interrogatorio. Adopta decúbito lateral derecho con leve flexión de caderas.',
  'fil.apellidos': 'Quispe Mamani',
  'fil.nombres': 'Rosa',
  'fil.edad': '55',
  'fil.sexo': 'Femenino',
  'fil.raza': 'Mestiza',
  'fil.lugar_nacimiento': 'Juliaca',
  'fil.fecha_nacimiento': '1971-03-12',
  'fil.lugar_procedencia': 'Puno',
  'fil.estado_civil': 'Casado',
  'fil.grado_instruccion': 'Secundaria completa',
  'fil.ocupacion': 'Comerciante',
  'fil.idioma': 'Castellano | Quechua',
  'fil.religion': 'Católica',
  'fil.informante': 'Directo, el propio paciente',
  'fil.fecha_ingreso': '2026-09-15',
  'fil.fecha_elaboracion': '2026-09-16',
  'fil.elaborado_por': 'Estudiante de Medicina UNA Puno',
  'ea.tiempo_valor': '3',
  'ea.tiempo_unidad': 'días',
  'ea.forma_inicio': 'Insidioso',
  'ea.curso': 'Progresivo',
  'ea.signos_sintomas':
    'Lumbalgia opresiva de intensidad 5/10 en la escala visual análoga (3 días) | Dorsalgia irradiada desde la región lumbar (2 días) | Limitación de la flexión del tronco (2 días)',
  'ea.sintomas_accesorios': 'Contractura de la musculatura paravertebral lumbar (3 días) | Sueño no reparador por el dolor (2 días)',
  'ea.sintoma_guia': 'Lumbalgia',
  'ea.relato_cronologico':
    'Paciente refiere que hace tres días, tras cargar mercadería, presenta lumbalgia de inicio insidioso, de tipo opresivo, de intensidad 5/10 en la escala visual análoga, que se irradia a la región dorsal, se exacerba con la flexión del tronco y la bipedestación prolongada, y cede parcialmente con el reposo en decúbito. Se automedica con naproxeno 550 mg vía oral cada 12 horas, con mejoría parcial.\nHace un día el dolor se intensifica hasta 7/10 y limita la deambulación, motivo por el que acude a consulta. Actualmente persiste la lumbalgia irradiada a la región dorsal, sin parestesias ni alteración del control de esfínteres.',
  'fb.apetito': 'Conservado',
  'fb.sed': 'Conservada',
  'fb.sueno': 'No reparador',
  'fb.heces_frec': '1',
  'fb.heces_bristol': 'Bristol 4',
  'fb.heces_car': 'Normales',
  'fb.orina_car': 'Normal',
  'fb.peso_var': 'Sin variación',
  'apn.vivienda_material': 'Adobe | Techo de calamina',
  'apn.vivienda_servicios': 'Agua de red pública | Desagüe | Luz eléctrica',
  'apn.tabaco': 'No fuma',
  'apn.alcohol': 'Consumo ocasional o social',
  'afi.menarquia': '13',
  'afi.menopausia': 'Sí',
  'afi.alergias': 'No refiere',
  'apa.hta': 'Sí, en tratamiento',
  'apa.hta_detalle': 'Desde 2019, enalapril 10 mg vía oral cada 12 horas',
  'apa.diabetes': 'Niega',
  'efg.estado_general': 'Regular',
  'efg.estado_nutricional': 'Bueno',
  'efg.estado_hidratacion': 'Bueno',
  'efg.conciencia': 'Lúcido',
  'efg.pa_sistolica': '140',
  'efg.pa_diastolica': '90',
  'efg.fc': '82',
  'efg.fr': '18',
  'efg.temperatura': '36.6',
  'efg.sato2': '93',
  'efg.peso': '68',
  'efg.talla': '1.52',
  'efg.glasgow_ao': '4',
  'efg.glasgow_rv': '5',
  'efg.glasgow_rm': '6',
  'efg.eva': 'Intensidad 7/10 en la escala visual análoga',
  'efg.llenado_capilar': 'Menor de 2 segundos',
  'efr.mid': 'Sin edema, sin signos de insuficiencia venosa. Pulsos pedios presentes.',
  'efr.fuerza': 'Fuerza muscular 5/5',
  'efr.pulsos': 'Pulsos 2+/4+',
  'efr.torax_mv': 'Murmullo vesicular conservado en ambos campos pulmonares',
  'efr.torax_agregados': 'Sin ruidos agregados',
  'efr.columna':
    'Conserva curvaturas fisiológicas. Dolor a la palpación de apófisis espinosas y musculatura paravertebral en región lumbar, a predominio izquierdo, con contractura paravertebral. Movilidad limitada a la flexión por dolor. Lasègue negativo bilateral.',
  'efr.edema_godet': 'Edema +/++++ hasta tobillos, bilateral, con fóvea',
  'dx.resumen':
    'Mujer de 55 años, hipertensa en tratamiento, con lumbalgia de tres días de evolución, de inicio insidioso y curso progresivo, irradiada a la región dorsal, que se exacerba con la flexión del tronco. Al examen, dolor a la palpación paravertebral lumbar izquierda con contractura muscular y Lasègue negativo bilateral.',
  'dx.presuntivo': 'Lumbalgia mecánica aguda',
  'dx.sindromico': 'Síndrome doloroso lumbar',
};
